// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi3RFzXbP4rLjUwZ1fiSKtxPF_eFW7hvY',
    appId: '1:90702839680:web:9197a0f1fc5c2b76324b65',
    messagingSenderId: '90702839680',
    projectId: 'proje1-78bce',
    authDomain: 'proje1-78bce.firebaseapp.com',
    storageBucket: 'proje1-78bce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl19Em7Ch-CBhkTgRuKSiWH7eNhUz1yMI',
    appId: '1:90702839680:android:ea8a096781236807324b65',
    messagingSenderId: '90702839680',
    projectId: 'proje1-78bce',
    storageBucket: 'proje1-78bce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtPfszTWhAnrDngLWHY-WwM47ZErRRXgQ',
    appId: '1:90702839680:ios:268c4934858f6f84324b65',
    messagingSenderId: '90702839680',
    projectId: 'proje1-78bce',
    storageBucket: 'proje1-78bce.firebasestorage.app',
    iosBundleId: 'com.example.deneme7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtPfszTWhAnrDngLWHY-WwM47ZErRRXgQ',
    appId: '1:90702839680:ios:268c4934858f6f84324b65',
    messagingSenderId: '90702839680',
    projectId: 'proje1-78bce',
    storageBucket: 'proje1-78bce.firebasestorage.app',
    iosBundleId: 'com.example.deneme7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi3RFzXbP4rLjUwZ1fiSKtxPF_eFW7hvY',
    appId: '1:90702839680:web:63e3ff017c5ee801324b65',
    messagingSenderId: '90702839680',
    projectId: 'proje1-78bce',
    authDomain: 'proje1-78bce.firebaseapp.com',
    storageBucket: 'proje1-78bce.firebasestorage.app',
  );

}